# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[(b'float', b'Float'), (b'setting', b'Project setting'), (b'int', b'Integer'), (b'bool', b'True/False'), (b'str', b'String')], default=b'str', max_length=16)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('plugin', models.CharField(blank=True, max_length=64)),
                ('doc', models.TextField(blank=True, verbose_name=b'Description')),
                ('kwargs', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='argument',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Function'),
        ),
    ]
