# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name=b'Time')),
                ('type', models.CharField(choices=[(b'testing', b'testing'), (b'calibration', b'calibration'), (b'validation', b'validation'), (b'prediction', b'prediction')], default=b'testing', max_length=32, verbose_name=b'Type')),
                ('notes', models.TextField(blank=True, verbose_name=b'Notes')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
